### ISSUE TITLE
Lexi

### ISSUE THREAD

**Issue by dgerian** [madeulook/web-ui#12]

**Comment by dgerian** [comment]
Alexis : (she has decided to go by her full name lol)
Alexis also attended the School of Botanical and Medical Aesthetics of Denver.
Her artistic talents are evident in all her work.  She specializes in lash extensions and custom brow shaping, but also offers Dermaplaning and Microdermabrasion as part of her services.

**Comment by milehimikey** [comment]
sure she doesn't want something like...the artist formerly known as alexis? ;)

**Comment by dgerian** [comment]
omg we should do that.  the artist formerly known as lexi  she would die,
lol


On Sun, May 8, 2016 at 3:30 PM, MiKey <notifications@github.com> wrote:

> sure she doesn't want something like...the artist formerly known as
> alexis? ;)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/madeulook/web-ui/issues/12#issuecomment-217747378>
>



-- 
*Danielle Gerian*
*Broker Associate *
*Remax Traditions, Inc.*
*303-618-5334 cell*

**Comment by dgerian** [comment]
@milehimikey  I wonder if we should remove the circles with our pics and where it says "great", "smarter" etc...  I don't want it to look too much like "center of attention" in that respect.  Also, I'm not crazy about the font...it's kind of hard to read in the cursive where the intros are... i know i didn't do  a good job helping find a font.  The only one I know I like is "expresso" on vista print lol

**Comment by dgerian** [comment]
@milehimikey oh and can we add the pic of audrey hepburn to the carousel?? I know I have to buy it somehow so I need to find it again.

**Comment by milehimikey** [comment]
@dgerian  opening 2 new tickets now for fonts and the "circles the pics" topics. We can try a few different things on each.
