### ISSUE TITLE
featurettes

### ISSUE THREAD

**Issue by dgerian** [madeulook/web-ui#16]
Lash Extensions - Say goodbye to mascara! Using synthetic mink, an extension is applied to each individual lash creating a natural look without causing damage to the natural lash!  We have a variety of lash lengths and curl to fit your style and personality!

Lash Lift - This treatment will last 8 to 10 weeks! A great alternative to extensions for those clients who already have the length, but want to ditch the mascara and curler!

Lash & Brow tinting - This service is great for clients who get tired of filling in those brows and wearing mascara everyday.  

Brow shaping -  Brows frame those beautiful eyes and deserve to be groomed! Waxing and tweezing done to achieve the perfect arch and a tint to fill in areas needed.

Facial waxing

Microdermabrasion - Exfoliation is essential to skin care! Removes those dead skin cells and increase circulation to the skin. No down time and provides instant results.

Dermaplaning -This is a safe, non evasive exfoliation treatment with no down time and immediate results! Dermaplaning promotes soft skin by removing the soft facial hair which can trap oils and dirt on skin.

02 Lift - This luxurious skin care treatment infuses oxygen, plant-derived stem cells, peptides and a high concentration of enzymatic botanicals into the skin leaving it luminous, refreshed & rejuvenated

**Comment by milehimikey** [comment]
Perfect. Exactly the kind of stuff needed here...add pics too probably?

**Comment by dgerian** [comment]
Yes. Pics :)

On Sunday, April 17, 2016, MiKey <notifications@github.com> wrote:

> Perfect. Exactly the kind of stuff needed here...add pics too probably?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/madeulook/web-ui/issues/16#issuecomment-211053810>
>


-- 
*Danielle Gerian*
*Broker Associate *
*Remax Traditions, Inc.*
*303-618-5334 cell*
